apiVersion: v1
kind: Service
metadata:
  labels:
    app: microservice
  name: microservice
  namespace: default
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: microservice
  sessionAffinity: None   ## from web application if would want to send the request to same server for session
  type: LoadBalancer