apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: microservice
  name: microservice
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice       ## the deployment should be applied for all pods with label as provided. 
                              ## spec.selector.matchLabels.app = spec.template.labels.app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: microservice     ## For an entire pod we are adding label
    spec:
      containers:
      - image: jannusuraj/microservice:1.0.0    ## container image to be deployed
        imagePullPolicy: IfNotPresent           ## If the image is not present in local then pull from docker hub [Always,IfNotPresent]
        name: microservice
        readinessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/readiness
        livenessProbe:
          httpGet:
            port: 8080
            path: /actuator/health/liveness
        env:
        - name: URL
          value: http://localhost:8080
      restartPolicy: Always                     ## restart policy for pods