apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
data:
  mongo-root-username: dXNlcm5hbWU=   #    echo -n "username" | base64
  mongo-root-password: cGFzc3dvcmQ=   #    echo -n "password" | base64