apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  namespace: project1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: nginx-container
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "512m"
          limits:
            memory: "128Mi"
            cpu: "1024m"