apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-rc
  namespace: project1
  labels:
    app: nginx-rc-server
spec:
  replicas: 3
  selector:
    app: server
  template:
    metadata:
      name: nginx-pod
      labels:
        app: server
    spec:
      containers:
      - name: nginx-container
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "64Mi"
            cpu: "512m"
          limits:
            memory: "128Mi"
            cpu: "1024m"